   location /youtube-dl/ {
	allow 127.0.0.1;
	deny all;

        proxy_pass http://localhost:8421/;
        proxy_set_header SCRIPT_NAME youtube-dl;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
   }
