# Generated by Django 4.2.30 on 2026-07-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloaderfe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='log_line',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='QUEUED', max_length=100),
        ),
    ]
